export let GET_TASK_REQUEST = "GET_TASK_REQUEST";
export let GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export let GET_TASK_ERROR = "GET_TASK_ERROR";

export let POST_TASK_REQUEST = "POST_TASK_REQUEST";
export let POST_TASK_SUCCESS = "POST_TASK_SUCCESS";
export let POST_TASK_ERROR = "POST_TASK_ERROR";

export let UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export let UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export let UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

export let DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export let DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export let DELETE_TASK_ERROR = "DELETE_TASK_ERROR";
